# Generated by Django 2.1 on 2019-02-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('unique_id', models.CharField(default='11b875db', editable=False, max_length=100, unique=True)),
                ('answers', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['question'],
            },
        ),
    ]
